src/Entity/Commentary.php
<?php
/**
 * Created by PhpStorm.
 * User: BKN1402
 * Date: 29.01.2018
 * Time: 19:28
 */

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Commentary
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type = "datetime", name = "published_at")
     */
    private $postedAt;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @var Post
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="comments")
     * @ORM\JoinColumn(name="post_id", referencedColumnName="id")
     */
    private $post;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Commentary
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPostedAt()
    {
        return $this->postedAt;
    }

    /**
     * @param mixed $postedAt
     * @return Commentary
     */
    public function setPostedAt($postedAt)
    {
        $this->postedAt = $postedAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return Commentary
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return Post
     */
    public function getPost(): Post
    {
        return $this->post;
    }

    /**
     * @param Post $post
     * @return Commentary
     */
    public function setPost(Post $post): Commentary
    {
        $this->post = $post;
        return $this;
    }

    /**
     * @return string
     */
    public function getMessage():? string
    {
        return $this->message;
    }

    /**
     * @param string $message
     * @return Commentary
     */
    public function setMessage(string $message): Commentary
    {
        $this->message = $message;
        return $this;
    }


}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type = "datetime", name = "published_at")
     */
    private $postedAt;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $heading;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentary", mappedBy="post")
     * @ORM\OrderBy({"name" = "DESC"})
     *
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getPostedAt()
    {
        return $this->postedAt;
    }

    /**
     * @param mixed $postedAt
     * @return Post
     */
    public function setPostedAt($postedAt)
    {
        $this->postedAt = $postedAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getHeading()
    {
        return $this->heading;
    }

    /**
     * @param mixed $heading
     * @return Post
     */
    public function setHeading($heading)
    {
        $this->heading = $heading;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ? string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Post
     */
    public function setDescription(string $description): Post
    {
        $this->description = $description;
        return $this;
    }

    public function getShorts(): ?string
    {
        $paragraphs = explode("\n", $this->description, 2);
        list($first) = $paragraphs;

        return $first;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param mixed $comments
     * @return Post
     */
    public function setComments($comments)
    {
        $this->comments = $comments;
        return $this;
    }


    }

src/Form/CommentType.php
<?php
/**
 * Created by PhpStorm.
 * User: BKN1402
 * Date: 29.01.2018
 * Time: 21:18
 */

namespace App\Form;


use App\Entity\Commentary;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Commentary::class,
        ));
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('postedAt')
            ->add('name')
            ->add('message')
        ;
    }
}

src/Form/PostType.php
<?php
/**
 * Created by PhpStorm.
 * User: BKN1402
 * Date: 09.01.2018
 * Time: 21:08
 */
namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Post::class,
        ));
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('postedAt')
            ->add('heading')
            ->add('description')
        ;
    }


}

src/Controller/BlogController.php
<?php
// src/Controller/BlogController.php
namespace App\Controller;

use App\Entity\Commentary;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function listBlog()
    {
        $posts = $this->getDoctrine()
            ->getRepository(Post::class)
            ->findBy([], ['postedAt' => 'DESC']);

        return $this->render('blog/list.html.twig', ['posts' => $posts]);
    }

    /**
     * @Route("/post/{id}", name="post_show")
     */
    public function show(Post $post, Request $request, EntityManagerInterface $em)

    {
        $commentary = new Commentary();
        $commentary->setPost($post);
        $form = $this->createForm(CommentType::class, $commentary);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($commentary);
            $em->flush();

            return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
        }


        return $this->render('post/show.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);
    }

    /**
     * @Route("/create", name="create_post")
     *
     * @param Request $request
     */
    public
    function create(Request $request, EntityManagerInterface $em)
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
        }

        return $this->render('blog/form.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit_post")
     *
     * @param Request $request
     */
    public
    function editPost(Post $post, Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
        }

        return $this->render('blog/edit.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);

    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MyBlog{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <style>
            body
            {
                margin-top: 75px;
                background-image:url({{ asset('image/IMG_4727.jpg') }});
                background-attachment: fixed;
                background-repeat: no-repeat;
                background-position: left;
                background-size: 20%;
            }
        </style>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=""></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{{ path('homepage')}}", style="padding: 7px" ><img src="{{ asset('image/Logo.png') }}" style="height: 30px"></a></li>
                <li><a href="{{ path('homepage')}}">Головна</a></li>
                <li><a href="{{ path('create_post')}}">Додати пост</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block body %}

{% endblock %}

<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
        crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

{% block javascripts %}{% endblock %}
</body>
</html>

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container-fluid">
        {% for message in app.flashes('info') %}
            <p class="bg-success">{{ message }}</p>
        {% endfor %}

        <div class="row">
            <div class="col-xs-3 col-md-3"></div>
            <div class="col-xs-9 col-md-6">
                <h3>Редагувати пост </h3>
                {{ form_start(form) }}
                {{ form_widget(form) }}
                <a href="{{ '/edit/{id}' }}">
                    <button type="submit" class="btn btn-default"> Зберегти зміни </button>
                </a>
                <a href="{{ '/post/{id}' }}">
                    <button type="submit" class="btn btn-default"> Повернутись к перегляду поста </button>
                </a>
                {{ form_end(form) }}
                <p style="margin-top: 25px">
                    <a href="{{ '/' }}">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-home"></span>  Повернутись на головну
                        </button>
                    </a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    {{ 'Редагувати'}} {{  post.heading }}
{% endblock %}

templates/blog/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% endblock %}

{% block title %}

{% endblock %}

templates/blog/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    MyBlog
{% endblock %}

{% block body %}

    <div class="col-xs-3 col-md-3"></div>
    <div class=".col-xs-9 col-md-9">
        {% for post in posts %}
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>{{ post.heading }}</h3>
                        <p>{{ post.postedAt|date }}</p>
                        <p>{{ post.shorts }}</p>
                        <p>
                            <a href="{{ path('post_show', {'id':post.id}) }}" class="btn btn-default" role="button">
                                 Читати далі...</a>
                        </p>
                        <a href="{{ path('post_show', {'id':post.id}) }}">Количество комментариев <span class="badge">{{ post.comments.count }}</span></a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ post.heading }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="col-xs-3 col-md-3"></div>
        <div class=".col-xs-9 col-md-9">
            <h4>Новини</h4>
            <h3>{{ post.heading }}</h3>
            <p>{{ post.postedAt|date }}</p>
            <p>{{ post.description }}</p>
            <p>
                <a href="{{ path('edit_post', {'id':post.id}) }}"
                   class="btn btn-default " role="button">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Редагувати
                </a>
            </p>
            <p>
                <a href="{{ path('homepage') }}" class="btn btn-default" role="button">
                    <span class="glyphicon glyphicon-home"></span> Повернутись на головну</a>
            </p>
        </div>
        <div class="col-xs-3 col-md-3"></div>
        <div class=".col-xs-9 col-md-9">
            <h2 >Нові коментарії</h2>
            <div class=".col-xs-9 col-md-9">
                {% for commentary in post.comments %}
                    <div class="thumbnail">
                        <div class="caption">
                            <h3>{{ commentary.name }}</h3>
                            <p>{{ commentary.postedAt|date }}</p>
                            <p>{{ commentary.message }}</p>
                        </div>
                    </div>
                {% endfor %}
                <p>
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                <p>
                    <a href="{{ '/commentary/{id}' }}">
                        <button type="submit" class="btn btn-default"> Додати новій коментарій </button>
                    </a>
                </p>
                    {{ form_end(form) }}
                </p>

            </div>


        </div>

    </div>
{% endblock %}